# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 */4 * * *" # Executes every 4 hour.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Contents
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python Packages Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        run: python update_db.py
        env:
          URL: ${{ secrets.URL }}
          KEY: ${{ secrets.KEY }}
